### ISSUE TITLE
Support GitHub discussions

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-github#43]
Probably fairly important to help moderate the lands. We can wait until there is an actual API though

**Comment by Half-Shot** [comment]
https://docs.github.com/en/graphql/guides/using-the-graphql-api-for-discussions

**Comment by shafqatevo** [comment]
Hi @Half-Shot, thanks for this work! Will be definitely useful for many open source projects.

Is this feature available now in any shape or form? Which client to use and how exactly to set up?

**Comment by Half-Shot** [comment]
It's still a bit on the testing side. GitHub *just* made their discussions webhooks available so we can start playing with it now. https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#discussion
