### ISSUE TITLE
Messages multiply in new rooms

### ISSUE THREAD

**Issue by turt2live** [Half-Shot/matrix-github#56]
![image](https://user-images.githubusercontent.com/1190097/111570786-28c23a00-876b-11eb-96e5-0beb60d8ccf4.png)
![image](https://user-images.githubusercontent.com/1190097/111570807-3081de80-876b-11eb-858f-2d06e556d2d0.png)

The logs keep adding one of these lines with each new comment:
```
INFO 03:52:32:392 [GithubBridge] New connected added to !viChOTXZbGFChCWzqi:t2bot.io: GitHubIssue turt2live/test#35
INFO 03:52:32:393 [GithubBridge] New connected added to !viChOTXZbGFChCWzqi:t2bot.io: GitHubIssue turt2live/test#35
INFO 03:52:32:394 [GithubBridge] New connected added to !viChOTXZbGFChCWzqi:t2bot.io: GitHubIssue turt2live/test#35
INFO 03:52:32:396 [GithubBridge] New connected added to !viChOTXZbGFChCWzqi:t2bot.io: GitHubIssue turt2live/test#35
```

**Comment by turt2live** [comment]
Looks like it's incrementing `comments_processed` in the state event, which is causing rebridges

**Comment by Half-Shot** [comment]
ah this would be why I disabled that code..

**Comment by Half-Shot** [comment]
Fixed by https://github.com/Half-Shot/matrix-github/commit/4b7978650b70319b3d63317a6ba421992e9a6106
